apiVersion: apps/v1
kind: Deployment
metadata:
  name: dostavki-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dostavki
  template:
    metadata:
      labels:
        name: dostavki
    spec:
      containers:
        - name: default
          image: korchasa/dostavki:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8090
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http