apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dostavki
  annotations:
    {{ if .Values.ingress.tlsSecret -}}
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
    {{- end }}
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - "{{ .Values.ingress.hostname }}"
      {{ if .Values.ingress.tlsSecret -}}
      secretName: "{{ .Values.ingress.tlsSecret }}"
      {{- end }}
  rules:
    - host: "{{ .Values.ingress.hostname }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: dostavki
              servicePort: 80

