apiVersion: v1
kind: Service
metadata:
  name: dostavki
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: dostavki
    app.kubernetes.io/instance: dostavki