name: Create Docker image

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Log into hub.docker.com
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - name: Build the Docker image
        run: docker build . --tag korchasa/dostavki:$GITHUB_RUN_NUMBER
      - name: Push Docker image
        run: docker push korchasa/dostavki:$GITHUB_RUN_NUMBER

